#pragma once
#include "Base.h"

namespace textureLoaderNS
{
	enum TEXTURE_NUMBER {
		TOON_OUT_LINE,
		TOON_SHADE,
		UI_RECURSION_BICYCLE,
		UI_RECURSION_BLACK_PHONE,
		UI_RECURSION_CHEWING_GUM,
		UI_RECURSION_FAN,
		UI_RECURSION_KENDAMA,
		UI_RECURSION_NAWATOBI,
		UI_RECURSION_NINGEN,
		UI_RECURSION_RABBIT_DOLL,
		UI_RECURSION_SOCCER_BALL,
		UI_RECURSION_TELEVISION,
		UI_RECURSION_XMAS_TREE,
		RECURSION,
		UI_COLONY_HP,
		UI_MISSILE,
		UI_WEAPON,
		UI_GAUGE_BAR,
		UI_GAUGE_BASE,
		UI_GAUGE_COVER,
		UI_CHARA_SELECT_BAR,
		UI_CHARA_SELECT_BAR2,
		UI_CHARA_SELECT_NO,
		UI_CHARA_SELECT_NO2,
		UI_CHARA_SELECT_CURSOR,
		UI_CHARA_SELECT_CURSOR2,
		UI_CHARA_SELECT_LOGO,
		UI_CHARA_SELECT_BG,
		UI_CHARA_SELECT_TIMER,
		SPRITE,
		RING,
		UV_GRID,
		SPLASH,
		TITLE_POS,
		TITLE_GAME,
		TITLE_TUTORIAL,
		TITLE_OPERATION,
		TITLE_CREDIT,
		TITLE_GAMEEND,
		TITLE_GAME_B,
		TITLE_TUTORIAL_B,
		TITLE_OPERATION_B,
		TITLE_CREDIT_B,
		TITLE_GAMEEND_B,
		TUTORIAL,
		RESULT,
		KEY_OPE,
		PAD_OPE,
		CREDIT,
		WHITE_TEXTURE,
		LIGHT001,
		HP_EFFECT,
		TARGET,
		POSE,
		SELECT,
		SELECT_PLAYER,
		SELECT_PLAYER2,
		MAX_TEXTURE,
	};
}

class TextureLoader : public Base
{
private:
	const char* textureName[textureLoaderNS::MAX_TEXTURE];
	LPDIRECT3DTEXTURE9 texture[textureLoaderNS::MAX_TEXTURE];
public:
	TextureLoader();
	~TextureLoader();

	void load(LPDIRECT3DDEVICE9 device);
	void release();

	LPDIRECT3DTEXTURE9* getTexture(int textureNo) { return &texture[textureNo]; }
};